cameras:
  - name: "Riksgransen"
    snapshotUrl: "https://api.trafikinfo.trafikverket.se/v2/Images/TrafficFlowCamera_39636488.Jpeg?type=fullsize&maxage=140"
    interval: "*/10 * * * *"
    delete: true

  - name: "Maldives"
    snapshotUrl: "https://cdn.skylinewebcams.com/live814.webp"
    interval: "*/1 * * * *"
    timelapseInterval: "45 0,12,17 * * *"
    delete: false

outputDir: "/tmp/timelapser"
interval: "*/5 * * * *"
timelapseInterval: "* 24,12 * * * *"
frameDuration: 0.041667
